### ISSUE TITLE
Counter button not deactivating on time up

### ISSUE THREAD

**Issue by alexisgarland** [johndeverall/BehaviourCoder#1]

**Comment by johndeverall** [comment]
I released a new version just now. I think it is fixed in the new one. Please check.

**Comment by alexisgarland** [comment]
Looks good; didn't resolve this issue though - and actually if you click two consecutively fast enough, it sometimes doesn't register either.  This is really only an issue at very high speeds though, when people are likely to be keying anyway. (Key shortcuts do NOT produce this issue.) I'd leave this as an open issue for whomever gets involved in making this modular.

**Comment by johndeverall** [comment]
Are we talking about the same issue?
